version: "3.3"

services:
  az-template:
    image: aztemplate:latest
#    command: /etc/init.d/nginx start
    ports:
      - 8090:80
    environment:
      - ENVIRONMENT=dev
    container_name: az-template
    tty: true
