#!/bin/sh
AZ_IMAGE_NAME="aztemplate"
AZ_CONTAINER_NAME="az-template"
alias setlocal="cp -f docker-compose-local.yml docker-compose.yml"
alias setprod="cp -f docker-compose-production.yml docker-compose.yml"
alias dbuild="docker-compose build"
alias dncbuild="docker-compose build --no-cache"
alias drun="docker-compose up -d"
alias dclear="docker container stop ${AZ_CONTAINER_NAME} ; docker container rm ${AZ_CONTAINER_NAME}"
alias dsh="docker exec -it ${AZ_CONTAINER_NAME} bash"
alias dprune="docker container prune ; docker image prune"
